/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BarRouteImport } from './routes/bar'
import { Route as HisobotRouteImport } from './routes/hisobot'
import { Route as SozlamalarRouteImport } from './routes/sozlamalar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BarRoute = BarRouteImport.update({
  id: '/bar',
  path: '/bar',
  getParentRoute: () => rootRouteImport,
} as any)
const HisobotRoute = HisobotRouteImport.update({
  id: '/hisobot',
  path: '/hisobot',
  getParentRoute: () => rootRouteImport,
} as any)
const SozlamalarRoute = SozlamalarRouteImport.update({
  id: '/sozlamalar',
  path: '/sozlamalar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bar': typeof BarRoute
  '/hisobot': typeof HisobotRoute
  '/sozlamalar': typeof SozlamalarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bar': typeof BarRoute
  '/hisobot': typeof HisobotRoute
  '/sozlamalar': typeof SozlamalarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bar': typeof BarRoute
  '/hisobot': typeof HisobotRoute
  '/sozlamalar': typeof SozlamalarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bar' | '/hisobot' | '/sozlamalar'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bar' | '/hisobot' | '/sozlamalar'
  id: '__root__' | '/' | '/bar' | '/hisobot' | '/sozlamalar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BarRoute: typeof BarRoute
  HisobotRoute: typeof HisobotRoute
  SozlamalarRoute: typeof SozlamalarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bar': {
      id: '/bar'
      path: '/bar'
      fullPath: '/bar'
      preLoaderRoute: typeof BarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hisobot': {
      id: '/hisobot'
      path: '/hisobot'
      fullPath: '/hisobot'
      preLoaderRoute: typeof HisobotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sozlamalar': {
      id: '/sozlamalar'
      path: '/sozlamalar'
      fullPath: '/sozlamalar'
      preLoaderRoute: typeof SozlamalarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BarRoute: BarRoute,
  HisobotRoute: HisobotRoute,
  SozlamalarRoute: SozlamalarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
